config/routes.rb
Rails.application.routes.draw do
  resources :notes, except: [:index]
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :description, presence: true
  validates :color, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :notes, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      @notes = current_user.notes.all
    end
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: %i[ show edit update destroy ]

  # GET /notes/1 or /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = current_user.notes.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes or /notes.json
  def create
    @note = current_user.notes.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to note_url(@note), notice: "Note was successfully created." }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1 or /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to note_url(@note), notice: "Note was successfully updated." }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1 or /notes/1.json
  def destroy
    @note.destroy

    respond_to do |format|
      format.html { redirect_to notes_url, notice: "Note was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def note_params
      params.require(:note).permit(:title, :description, :color, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/home/_landing.html.erb
<div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-4">
  <div class="grid grid-cols-1 md:grid-cols-2">
    <div class="flex flex-col place-content-center items-center md:items-start py-16">
      <h1 class="text-6xl font-light leading-7 text-black">Aura Notes</h1>
      <h2 class="mt-6 text-2xl font-light leading-2 text-black">Effortlessly organize your notes</h2>
      <div class="mt-8">
        <%= link_to 'Get Started', new_user_registration_path, class:'text-xl border border-black rounded-md py-2 px-6 hover:-ml-1 hover:-mt-1 hover:border-b-4 hover:border-r-4' %>
      </div>
    </div>

    <%= image_tag 'aura_notes_graphic.svg', class:'mx-auto w-96 md:w-full py-0 md:py-16' %>
  </div>
</div>

app/views/home/index.html.erb
<% if user_signed_in? && @notes.count > 0%>
  <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-12">

    <div id="notes" class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
      <%= link_to new_note_path, class:"flex flex-col gap-2 text-xl items-center place-content-center border border-dashed border-black rounded-md p-4 hover:border-solid hover:-ml-1 hover:-mt-1 hover:border-r-4 hover:border-b-4" do %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-10 h-10">
          <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v6m3-3H9m12 0a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
        </svg>
        Add Note
      <% end %>

      <% @notes.each do |note| %>
        <%= link_to note_path(note.id), class:"border border-black rounded-md p-4 #{note.color} hover:-ml-1 hover:-mt-1 hover:border-r-4 hover:border-b-4" do %>
          <div class="">
            <p class="text-2xl"><%= note.title.truncate(24) %><p>
            <p class="text-sm text-gray-600 font-medium"><%= note.created_at.strftime("%d %b") %><p>
            <p class="mt-3 text-gray-800"><%= note.description.truncate(100) %><p>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
<% else %>
  <%= render 'home/landing' %>
<% end %>

app/views/layouts/_header.html.erb
<nav class="bg-white shadow">
  <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
    <div class="flex h-20 justify-between">
      <div class="flex">
        <%= link_to 'Aura Notes', root_path, class:'flex flex-shrink-0 font-medium text-3xl items-center' %>
      </div>
      <div class="ml-6 flex items-center gap-4">
        <% if user_signed_in? %>
          <%= link_to 'Add Note', new_note_path, class:'border border-black rounded-md py-2 px-6 hover:-ml-1 hover:-mt-1 hover:border-b-4 hover:border-r-4' %>
          <%= link_to 'Log out', destroy_user_session_path, data: { "turbo-method": :delete }, class:'border border-black rounded-md py-2 px-6 hover:-ml-1 hover:-mt-1 hover:border-b-4 hover:border-r-4' %>
        <% else %>
          <%= link_to 'Log in', new_user_session_path, class:'border border-black rounded-md py-2 px-6 hover:-ml-1 hover:-mt-1 hover:border-b-4 hover:border-r-4' %>
        <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Aura Notes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= favicon_link_tag 'favicon.ico' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="flex place-content-center font-regular leading-8 bg-green-400"><%= notice %></p>
    <p class="flex place-content-center font-regular leading-8 bg-red-400"><%= alert %></p>
    
    <% unless controller_name == 'registrations' || controller_name == 'sessions' || controller_name == 'passwords' %>
      <%= render 'layouts/header' %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_with(model: note, class: "contents") do |form| %>
  <% if note.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
        <% note.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="flex flex-col my-4">
    <%= form.label :title %>
    <%= form.text_field :title,  class:'rounded-md border border-black mt-1 focus:ring-black' %>
  </div>

   <div class="flex flex-col my-4">
    <%= form.label :description %>
    <%= form.text_area :description, rows:5, class:'rounded-md border border-black mt-1 focus:ring-black' %>
  </div>

  <div class="flex flex-col my-4">
    <%= form.label :color, 'Select color' %>
    <div class="flex gap-4 my-1">
      <label class="flex items-center gap-1">
        <%= form.radio_button :color, 'bg-amber-300', class:'hidden' %>
        <div class="color-option bg-amber-300 h-8 w-8 rounded">
        </div>
      </label>

      <label class="flex items-center gap-1">
        <%= form.radio_button :color, 'bg-blue-300', class:'hidden' %>
        <div class="color-option bg-blue-300 h-8 w-8 rounded">
        </div>
      </label>

      <label class="flex items-center gap-1">
        <%= form.radio_button :color, 'bg-red-300', class:'hidden' %>
        <div class="color-option bg-red-300 h-8 w-8 rounded">
        </div>
      </label>

      <label class="flex items-center gap-1">
        <%= form.radio_button :color, 'bg-lime-300', class:'hidden' %>
        <div class="color-option bg-lime-300 h-8 w-8 rounded">
        </div>
      </label>

      <label class="flex items-center gap-1">
        <%= form.radio_button :color, 'bg-teal-300', class:'hidden' %>
        <div class="color-option bg-teal-300 h-8 w-8 rounded">
        </div>
      </label>

      <label class="flex items-center gap-1">
        <%= form.radio_button :color, 'bg-violet-300', class:'hidden' %>
        <div class="color-option bg-violet-300 h-8 w-8 rounded">
        </div>
      </label>
    </div>
  </div>

  <div class="inline">
    <%= form.submit class: "mt-2 border border-black bg-black text-white rounded-md py-3 px-6 hover:bg-gray-700" %>
  </div>
<% end %>

<style>
  .color-option {
    cursor: pointer;
  }

  input[type="radio"]:checked + .color-option {
    border: 2px solid black;
  }
</style>

app/views/notes/_note.html.erb
<div id="<%= dom_id note %>" class="border border-black rounded-md py-4 <%= note.color %>">
  <p class="text-3xl px-4 font-light">
    <%= note.title %>
  </p>

  <div class="border-t border-black w-full py-4"></div>

  <p class="text-base px-4">
    <%= note.description %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this note", note, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this note", edit_note_path(note), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/notes/edit.html.erb
<div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-4">
  <h1 class="text-4xl">Edit note</h1>

  <%= render "form", note: @note %>

  <%= link_to "Back to notes", root_path, class: "ml-2 mt-2 border border-black rounded-md py-3 px-6 hover:bg-gray-200" %>
</div>

app/views/notes/new.html.erb
<div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-4">
  <h1 class="text-4xl">New note</h1>

  <%= render "form", note: @note %>

  <%= link_to "Back to notes", root_path, class: "ml-2 mt-2 border border-black rounded-md py-3 px-6 hover:bg-gray-200" %>
</div>

app/views/notes/show.html.erb
<div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-4">
  <div class="flex flex-col py-8">
    <%= render @note %>

    <div class="flex mt-4">
      <%= link_to "Edit this note", edit_note_path(@note), class: "mt-2 border border-black bg-black text-white rounded-md py-3 px-6 hover:bg-gray-700" %>
      <%= link_to "Back to notes", root_path, class: "ml-2 mt-2 border border-black rounded-md py-3 px-6 hover:bg-gray-200" %>
    </div>

    <div class="mt-8">
      <%= button_to "Destroy this note", note_path(@note), method: :delete, class: "border border-red-500 bg-red-500 text-white rounded-md py-3 px-6 hover:border-red-700 hover:-ml-1 hover:-mt-1 hover:border-b-4 hover:border-r-4" %>
    </div>
  </div>
</div>